######################################################################
# Automatically generated by qmake (2.01a) mar oct 8 20:56:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edge.h graph.h mainwindow.h tspgraph.h vertex.h
FORMS += mainwindow.ui
SOURCES += edge.cpp graph.cpp main.cpp mainwindow.cpp tspgraph.cpp vertex.cpp
